# Generated by Django 5.0.2 on 2024-02-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.message')),
                ('firstMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member_conversations', to='Chat.user')),
                ('secondMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_member_conversations', to='Chat.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserConv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.conversation')),
                ('messageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.message')),
            ],
        ),
    ]
