# Generated by Django 5.0.2 on 2024-02-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconv',
            name='messageId',
        ),
        migrations.AddField(
            model_name='userconv',
            name='userId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Chat.user'),
        ),
        migrations.AlterField(
            model_name='userconv',
            name='convId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Chat.conversation'),
        ),
        migrations.CreateModel(
            name='MessageConv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Chat.conversation')),
                ('messageId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Chat.message')),
            ],
        ),
    ]
