# Generated by Django 5.0.2 on 2024-02-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_remove_userconv_messageid_userconv_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Chat.user'),
        ),
    ]
