# Generated by Django 5.0.2 on 2024-03-01 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_message_senderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastMessage',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.message'),
        ),
    ]
